### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lagauffregante** [BKthousand/variant16x-issues#4]
## Game Information: ##
***Minecraft Version:***
***Forge Version:***
***'Variant16x' Version:***

## How to reproduce the Crash: ##
*Please be as detailed as possible.*

## Game Logs: ##
*Please include your game logs with this report.*

**Comment by lagauffregante** [comment]
variant16x and TonsOfEnchants are not using the forge config system correctly.

**Comment by BKthousand** [comment]
Need more information.

**Comment by lagauffregante** [comment]
variant x16 and TonsOfEnchant are incompatible.

**Comment by BKthousand** [comment]
Unable to reproduce any issues with given information.
